import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';

const browser = await chromium.launch({ channel: 'chrome', headless: true, args: ['--enable-webgl', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
const page = await context.newPage();
const errors = [];
page.on('pageerror', error => errors.push(error.message));
try {
  await page.goto('http://localhost:5173/#welcome');
  await page.locator('canvas[data-character-canvas]').waitFor();
  await page.waitForFunction(() => document.querySelector('canvas')?.dataset.headYaw !== undefined);
  await page.screenshot({ path: 'artifacts/messenger-ni-kat-desktop.png', fullPage: true });
  await page.mouse.move(30, 130);
  await page.waitForFunction(() => Number(document.querySelector('canvas').dataset.headYaw) < -.15);
  const left = Number(await page.locator('canvas').getAttribute('data-head-yaw'));
  await page.mouse.move(1410, 800);
  await page.waitForFunction(() => Number(document.querySelector('canvas').dataset.headYaw) > .15);
  const right = Number(await page.locator('canvas').getAttribute('data-head-yaw'));
  assert.ok(right > left, '3D head follows pointer in both directions');
  await page.getByRole('button', { name: 'Pause character motion', exact: true }).click();
  await page.waitForFunction(() => Math.abs(Number(document.querySelector('canvas').dataset.headYaw)) < .02);
  await page.getByRole('button', { name: 'Resume character motion', exact: true }).click();
  console.log('PASS: real WebGL scene, head tracking left/right, pause/resume');
  await page.getByRole('button', { name: 'Create your account', exact: true }).click();
  await page.getByRole('button', { name: 'Ember', exact: true }).click();
  await page.getByRole('button', { name: 'amber hoodie', exact: true }).click();
  await page.getByRole('button', { name: 'Skin tone 3', exact: true }).click();
  await page.getByRole('button', { name: 'With glasses', exact: true }).click();
  await page.getByRole('button', { name: 'heart badge', exact: true }).click();
  await page.getByLabel('Full name', { exact: true }).fill('Kat Browser Test');
  await page.getByLabel('Custom contact number', { exact: true }).fill('2025550101');
  await page.getByLabel('Password', { exact: true }).fill('demo-test-password');
  assert.equal(await page.getByRole('button', { name: 'Create my account', exact: true }).isEnabled(), false);
  await page.getByText('This number is already taken.', { exact: true }).waitFor();
  const number = '889' + String(Date.now()).slice(-9);
  await page.getByLabel('Custom contact number', { exact: true }).fill(number);
  await page.screenshot({ path: 'artifacts/messenger-ni-kat-signup.png', fullPage: true });
  await page.getByRole('button', { name: 'Create my account', exact: true }).click();
  await page.waitForURL('**/#home');
  let user = await page.evaluate(() => JSON.parse(localStorage.getItem('loop-session')));
  assert.deepEqual(user.character, { style: 1, mood: 'amber', badge: 'heart', skin: 2, glasses: true });
  await page.reload();
  await page.getByRole('button', { name: 'Kat Browser Test profile' }).click();
  await page.getByRole('button', { name: 'Customize my character', exact: true }).click();
  await page.getByRole('button', { name: 'Nova', exact: true }).click();
  await page.getByRole('button', { name: 'No glasses', exact: true }).click();
  await page.getByRole('button', { name: 'Save character', exact: true }).click();
  user = await page.evaluate(() => JSON.parse(localStorage.getItem('loop-session')));
  assert.equal(user.character.style, 2);
  assert.equal(user.character.glasses, false);
  await page.getByRole('button', { name: 'Kat Browser Test profile' }).click();
  await page.getByRole('button', { name: 'Log out', exact: true }).click();
  await page.getByLabel('Custom contact number', { exact: true }).fill(number);
  await page.getByLabel('Password', { exact: true }).fill('demo-test-password');
  await page.getByRole('button', { name: 'Log in', exact: true }).click();
  await page.waitForURL('**/#home');
  user = await page.evaluate(() => JSON.parse(localStorage.getItem('loop-session')));
  assert.equal(user.character.style, 2);
  assert.equal(user.character.glasses, false);
  console.log('PASS: duplicate rejection, customized signup, reload, edit avatar, logout/login persistence');
  await page.goto('http://localhost:5173/#welcome');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.locator('canvas[data-character-canvas]').waitFor();
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'Mobile landing must not overflow');
  await page.screenshot({ path: 'artifacts/messenger-ni-kat-mobile.png', fullPage: true });
  await page.getByRole('button', { name: 'Create your account', exact: true }).click();
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'Mobile signup must not overflow');
  await page.screenshot({ path: 'artifacts/messenger-ni-kat-signup-mobile.png', fullPage: true });
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.mouse.move(380, 400);
  await page.waitForFunction(() => [...document.querySelectorAll('canvas[data-character-canvas]')].filter(c => c.getBoundingClientRect().width > 0).every(c => Math.abs(Number(c.dataset.headYaw)) < .02));
  console.log('PASS: mobile layouts and reduced motion preference');
  assert.deepEqual(errors, [], 'No JavaScript runtime errors');
  console.log('PASS: no runtime errors');
} finally {
  await browser.close();
}

