const fs = require('fs'), ts = require('typescript'), vm = require('vm'), assert = require('node:assert/strict');
const source = ts.transpileModule(fs.readFileSync('src/conversations.js','utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS } }).outputText;
const database = new Map([['users/a/contacts/b', { uid: 'b' }], ['users/b/contacts/a', { uid: 'a' }]]);
const auth = { currentUser: { uid: 'a', emailVerified: true, getIdToken: async () => 'token' } };
let writes = 0;
const sdk = { doc: (_, ...parts) => parts.join('/'), serverTimestamp: () => 'TIME', runTransaction: async (_, fn) => fn({ get: async path => ({ exists: () => database.has(path), data: () => database.get(path) }), set: (path, data) => { database.set(path, data); writes++; } }) };
const output = {};
vm.runInNewContext(source, { exports: output, require: name => name === 'firebase/firestore' ? sdk : { auth, db: {} } });
(async () => {
  const id = await output.openConversation('b');
  assert.equal(id, output.conversationId('b', 'a'));
  assert.equal(await output.openConversation('b'), id);
  auth.currentUser.uid = 'b';
  assert.equal(await output.openConversation('a'), id);
  assert.equal(writes, 1);
  assert.deepEqual(JSON.parse(JSON.stringify(database.get('conversations/' + id))), { participants: ['a', 'b'], createdAt: 'TIME' });
  assert.notEqual(output.conversationId('a_b', 'c'), output.conversationId('a', 'b_c'));
  await assert.rejects(output.openConversation('c'), /accepted contacts/);
  await assert.rejects(output.openConversation('b'), /accepted contact/);
  auth.currentUser.emailVerified = false;
  await assert.rejects(output.openConversation('a'), /verified email/);
  assert.equal(writes, 1);
  const contact = { id: 'b', name: 'dodlet', number: '333333', character: { badge: 'heart' } };
  for (const search of ['dodlet', 'DODLET', '333333', '  dodlet  ']) assert.equal(output.searchConversationPeople([], [contact], search)[0].id, 'b');
  assert.equal(output.searchConversationPeople([], [contact], '').length, 0);
  assert.equal(output.searchConversationPeople([{ ...contact, conversationId: id }], [contact], 'dodlet').length, 1);
  assert.equal(output.searchConversationPeople([{ ...contact, conversationId: id }], [], '')[0].conversationId, id);
  assert.equal(output.searchConversationPeople([], [contact], 'Emma Wilson').length, 0);
  console.log('PASS conversation creation, reverse/repeated opens, stored participants, collision resistance, contact/verification restrictions, name/number search and deduplication');
})().catch(error => { console.error(error); process.exitCode = 1; });
