import React, { useState } from 'react';
import { ArrowUpRight, ArrowRight, MessageCircle, Fingerprint, Sparkles } from 'lucide-react';
import Brand from './Brand';
import { Character, characters, defaultCharacter } from './Character';

export default function Welcome({ navigate }) {
  const [character, setCharacter] = useState(defaultCharacter);
  return <div className="welcome-page"><header className="welcome-header"><Brand /><nav aria-label="Main navigation"><button className="current" onClick={() => navigate('welcome')}>Home</button><button onClick={() => navigate('signup')}>Registration <ArrowUpRight size={13} /></button></nav><button className="welcome-login" onClick={() => navigate('login')}>Log in <ArrowRight size={16} /></button></header>
    <main className="welcome-hero"><section className="hero-copy"><span className="hero-eyebrow"><span /> YOUR PEOPLE. YOUR PERSONALITY.</span><h1>A little chat.<br />A lot of <em>you.</em></h1><p>A place for your everyday hellos and late-night stories. Create your character. Pick your number. Find your people.</p><button className="primary hero-cta" onClick={() => navigate('signup')}>Create your account <ArrowUpRight size={18} /></button><button className="explore-link" onClick={() => navigate('home')}>Take a look around <ArrowRight size={15} /></button><div className="hero-social"><span className="tiny-characters">{[0, 1, 2].map(style => <Character key={style} value={{ ...defaultCharacter, style, badge: 'none' }} />)}</span><span>Different personalities.<br /><strong>One place to connect.</strong></span></div></section>
    <div className="hero-character"><span className="hero-live-label">LIVE 3D · MOVE YOUR CURSOR</span><div className="orbital orbital-one" /><div className="orbital orbital-two" /><Character value={character} portrait /><div className="floating-chat float-left"><span>✦</span> 100% your kind of vibe.</div><div className="floating-chat float-right"><MessageCircle size={17} /> Hey, you! <span>♡</span></div><div className="hero-character-name"><span>MEET YOUR OTHER YOU</span><strong>{characters[character.style]} <span>✦</span></strong><div>{characters.map((name, style) => <button key={name} aria-label={`Preview ${name}`} aria-pressed={character.style === style} onClick={() => setCharacter({ ...character, style })} />)}</div></div></div>
    <section className="hero-invite"><span className="invite-symbol">✳</span><h2>Not just a profile.<br /><em>A personality.</em></h2><p>Your character is your first hello. Make it feel like you, right from signup.</p><button onClick={() => navigate('signup')}>Make your character <ArrowUpRight size={18} /></button><span className="invite-note">A little different. Just like you.</span></section></main>
    <section className="welcome-features" aria-label="Features"><div><Fingerprint /><span><strong>Your number, your choice</strong><small>Pick a unique number that feels like yours.</small></span></div><div><Sparkles /><span><strong>Show up as yourself</strong><small>A custom character with your own mood.</small></span></div><div><MessageCircle /><span><strong>Good conversations live here</strong><small>Find a friend. Send a hello. Stay close.</small></span></div></section><footer className="welcome-footer"><span>© {new Date().getFullYear()} Messenger Ni Kat</span><span>Made for connection. With a little character. <span>♡</span></span><button onClick={() => navigate('home')}>Explore demo <ArrowUpRight size={13} /></button></footer>
  </div>;
}

